# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1556016886);
user_pref("app.update.lastUpdateTime.background-update-timer", 1556017126);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1556017006);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1556016646);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1556016766);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 19);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.slowStartup.averageTime", 9490);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190218155749");
user_pref("browser.startup.homepage_override.mstone", "4.1.8");
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:28.4.0");
user_pref("extensions.lastAppVersion", "28.4.0");
user_pref("extensions.lastPlatformVersion", "4.1.8");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/palemoon/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"28.4.0\",\"st\":1550577399000}}}");
user_pref("idle.lastDailyNotification", 1556017496);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 8);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1556016613);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
